"""Win32 显示 API 常量和旋转映射。"""

# QueryDisplayConfig flags
QDC_ONLY_ACTIVE_PATHS = 1
QDC_ALL_PATHS = 2

# SetDisplayConfig flags
SDC_APPLY = 0x00000080
SDC_USE_SUPPLIED_DISPLAY_CONFIG = 0x00000040
SDC_SAVE_TO_DATABASE = 0x00000100
SDC_ALLOW_CHANGES = 0x00000400
SDC_VIRTUAL_MODE_AWARE = 0x00000800

# DisplayConfig device info types
DISPLAYCONFIG_DEVICE_INFO_GET_SOURCE_NAME = 1
DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME = 2
DISPLAYCONFIG_DEVICE_INFO_GET_ADAPTER_NAME = 4

# Mode info types
DISPLAYCONFIG_MODE_INFO_TYPE_SOURCE = 1
DISPLAYCONFIG_MODE_INFO_TYPE_TARGET = 2

# Rotation
DISPLAYCONFIG_ROTATION_IDENTITY = 1
DISPLAYCONFIG_ROTATION_ROTATE90 = 2
DISPLAYCONFIG_ROTATION_ROTATE180 = 3
DISPLAYCONFIG_ROTATION_ROTATE270 = 4

# Sentinel
DISPLAYCONFIG_PATH_MODE_IDX_INVALID = 0xFFFFFFFF

# Rotation convenience maps
ROTATION_MAP = {0: 1, 90: 2, 180: 3, 270: 4}
ROTATION_NAMES = {1: "normal", 2: "left", 3: "inverted", 4: "right"}
ROTATION_FROM_NAME = {"normal": 0, "left": 90, "inverted": 180, "right": 270}
ROTATION_DEGREES = {1: 0, 2: 90, 3: 180, 4: 270}

# ChangeDisplaySettingsEx
CDS_UPDATEREGISTRY = 0x00000001
DISP_CHANGE_SUCCESSFUL = 0
ENUM_CURRENT_SETTINGS = 0xFFFFFFFF

# Device name buffer size
CCHDEVICENAME = 32
